name: Create release pull requests

on:
  pull_request:
    branches:
      - dev
    types: [closed]

jobs:
  create-release-pr:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'main') == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get Version
        id: get_version
        uses: bbonkr/get-version-action@v1.0.1
        with:
          project: "./version.json"

      - name: Echo Version
        id: echo-version
        run: |
          echo "Version=${{ steps.get_version.outputs.version }}"

      - name: Create a release pull request
        uses: bakunyo/git-pr-release-action@v1.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}