name: Create Release

on:
  pull_request:
    types: [labeled]

jobs:
  create-release:
    if: github.event.label.name == 'release'
    runs-on: ubuntu-latest
    #nodeのバージョン設定 参考 https://docs.github.com/ja/free-pro-team@latest/actions/guides/building-and-testing-nodejs
    strategy:
      matrix:
        node-version: [13.x] 

    steps:
      - name: Checkout code
        uses: actions/checkout@master

      #yarnでのscriptの実施
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn gulp sass

      # release作成
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.pull_request.title }}
          release_name: ${{ github.event.pull_request.title }}
          body: ${{ github.event.pull_request.body }}
          draft: false
          prerelease: false

      # release用のzip作成 https://github.com/marketplace/actions/zip-release
      - name: Zip Release 
        uses: TheDoctor0/zip-release@0.4.1
        with:
          filename: 'release-test.zip' # ファイル名
          exclusions: '*.git* /*node_modules/* .editorconfig /*src/*scss/*' # 除外設定
          directory: '.'
          path: '.'
          type: 'zip'

      # releaseにzipファイルを添付
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./release-test.zip
          asset_name: release-test.zip
          asset_content_type: application/zip

      # main から dev へオートマージ
      - name: Extract branch name
        uses: mdecoleman/pr-branch-name@1.0.0
        id: extract_branch
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: yanamura/git-flow-merge-action@v1
        name: git-flow merge
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.extract_branch.outputs.branch }}
          # git-flowにおけるdevelopブランチの、あなたのリポジトリーにおける名称
          develop_branch: "dev"
          # git-flowにおけるmasterブランチの、あなたのリポジトリーにおける名称
          main_branch: "main"