name: get_version

on:
  push:
    branches:
      - dev

jobs:
  hello:
    name: HelloWorld sample
    runs-on: ubuntu-latest

    steps:
      - name: Get version
        uses: technote-space/get-next-version-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: echo ${{ NEXT_VERSION }}
