name: get_version

on:
  push:
    branches:
      - dev

jobs:
  hello:
    name: HelloWorld sample
    runs-on: ubuntu-latest

    steps:
      - name: get version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with: 
            path: './version.json'
            prop_path: 'version'
      - run: echo ${{steps.version.outputs.prop}}